<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>generator</AssemblyName>
    <RootNamespace>TestFileGenerator</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TestFileGenerator.Tests" />
    <InternalsVisibleTo Include="FileSorter.Tests" />
    <InternalsVisibleTo Include="FileSorter.Benchmarks" />
  </ItemGroup>

</Project>
