using FileSorter.Startup;

namespace FileSorter.Tests.Properties;

/// <summary>
/// Drives <see cref="Program.RunAsync"/> over generated bytes on real temp files, the
/// same entry point the end-to-end tests use, so a property failure reproduces the same
/// way a hand-written one would. Shared by every property test that needs a real sorted
/// file rather than one in-process type.
/// </summary>
internal static class PropertyHarness
{
    // An upper bound for a saturated thread pool, not an expectation of how long a run
    // takes: a few-kilobyte generated file sorts in milliseconds. It is short enough
    // that a genuinely hung run fails the property instead of stalling the suite.
    private static readonly TimeSpan BoundedWait = TimeSpan.FromSeconds(60);

    /// <param name="parallelism">
    /// <c>MemoryBudget.Calculate</c> derives the merge worker count from this and from
    /// the budget together, so a property that wants more than one merge worker at a
    /// chunk size small enough for a few-kilobyte file to produce several runs has to
    /// raise both.
    /// </param>
    public static async Task<byte[]> RunSorterAsync(
        byte[] input, long memoryBudgetBytes, int maxLineLength, CancellationToken ct, int parallelism = 2)
    {
        string directory = Path.Combine(Path.GetTempPath(), "FileSorterTests", Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(directory);
        try
        {
            string inputPath = Path.Combine(directory, "in.txt");
            string outputPath = Path.Combine(directory, "out.txt");
            string tempDirectory = Path.Combine(directory, "temp");
            await File.WriteAllBytesAsync(inputPath, input, ct);

            // Channels, not Akka: the two pipelines are shown to agree by their own
            // tests, and paying Akka's ActorSystem startup on every iteration would make
            // a few hundred iterations slow for a question already answered elsewhere.
            SorterOptions options = new(
                inputPath, outputPath, tempDirectory, memoryBudgetBytes, maxLineLength, parallelism, Pipeline.Channels);

            int exitCode = await Program.RunAsync(options, ct).WaitAsync(BoundedWait, ct);
            if (exitCode != 0)
            {
                throw new InvalidOperationException(
                    $"The sorter exited with code {exitCode} for a property-generated input; expected success.");
            }

            return await File.ReadAllBytesAsync(outputPath, ct);
        }
        finally
        {
            Directory.Delete(directory, recursive: true);
        }
    }
}
